name: build

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ windows, linux, darwin ]
        goarch: [ amd64 ]
        include:
          - goos: darwin
            goarch: arm64
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
        
    - name: Install dependencies
      run: go install -v ./...

    - name: Build
      run: go build -v -o out/filedrop-${{ matrix.goos }}-${{ matrix.goarch }}
      
    - name: Rename for Windows
      if: matrix.goos == 'windows'
      run: mv out/filedrop-${{ matrix.goos }}-${{ matrix.goarch }} out/filedrop-${{ matrix.goos }}-${{ matrix.goarch }}.exe
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: filedrop-${{ matrix.goos }}-${{ matrix.goarch }}
        path: out/*
        
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3

      - name: Show files
        run: |
          pwd
          find
      
      - name: Calc hash
        run: |
          mkdir out
          cp ./filedrop-linux-amd64/filedrop-linux-amd64 ./out/
          cp ./filedrop-windows-amd64/filedrop-windows-amd64.exe ./out/
          cp ./filedrop-darwin-amd64/filedrop-darwin-amd64 ./out/
          cp ./filedrop-darwin-arm64/filedrop-darwin-arm64 ./out
          cd out
          sha256sum * > sha256sum
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*
          draft: true
